---

- name: Create dhclient.conf
  template:
    src: dhclient.conf.j2
    dest: "{{ dhclient_config_file }}"
  notify: Restart dhclient

- name: Start dhclient
  service:
    name: "{{ dhclient_service }}"
    arguments: "{{ dhclient_interface }}"
    state: started
